### PR TITLE
Using .map instead of .forEach

### PR DESCRIPTION
**Pull request by ArtskydJ**
This cleans up the code a little bit

### CODE REVIEW

**Comment by ArtskydJ** [comment]
@danielmahon, @steelbrain thoughts?

**Comment by steelbrain** [comment]
Looks good to me, Daniel Mahon comes online once in a while so you might have to wait :)

**Comment by danielmahon** [comment]
@ArtskydJ thanks!

**Comment by ArtskydJ** [comment]
You're welcome!

**Pull request merged**
